name: "AMSExplorer"

on:
  workflow_dispatch:

jobs:
  test-building-devenv-2022:
    name: "Test building"
    runs-on: ${{ matrix.os }}
    env:
      DEVENV_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com
      SLN_PATH: src\AMSExplorer\AMSExplorer.sln
    strategy:
      matrix:
        os: [windows-2022]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup Nuget.exe
        uses: nuget/setup-nuget@v1
      - name: nuget restore
        shell: cmd
        run: nuget restore "%SLN_PATH%"
      - name: devenv setup
        shell: cmd
        run: |
          "%DEVENV_PATH%" /setup
      - name: compile debug
        shell: cmd
        run: |
          "%DEVENV_PATH%" "%SLN_PATH%" /build debug
      - name: compile release
        shell: cmd
        run: |
          "%DEVENV_PATH%" "%SLN_PATH%" /build release
  test-building-devenv-2019:
    name: "Test building"
    runs-on: ${{ matrix.os }}
    env:
      DEVENV_PATH: C:\Program Files\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.com
      SLN_PATH: src\AMSExplorer\AMSExplorer.sln
    strategy:
      matrix:
        os: [windows-2019]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
      - name: Setup Nuget.exe
        uses: nuget/setup-nuget@v1
      - name: nuget restore
        shell: cmd
        run: nuget restore "%SLN_PATH%"
      - name: devenv setup
        shell: cmd
        run: |
          "%DEVENV_PATH%" /setup
      - name: compile debug
        shell: cmd
        run: |
          "%DEVENV_PATH%" "%SLN_PATH%" /build debug
      - name: compile release
        shell: cmd
        run: |
          "%DEVENV_PATH%" "%SLN_PATH%" /build release
  test-building-msbuild:
    name: "Test building"
    runs-on: ${{ matrix.os }}
    env:
      SLN_PATH: src\AMSExplorer\AMSExplorer.sln
    strategy:
      matrix:
        os: [windows-2022, windows-2019]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: msbuild restore
      shell: cmd
      run: |
        msbuild /t:restore "%SLN_PATH%"
    - name: compile debug
      shell: cmd
      run: |
        msbuild "%SLN_PATH%" /p:Configuration=Debug
    - name: compile release
      shell: cmd
      run: |
        msbuild "%SLN_PATH%" /p:Configuration=Release