name: "Build TestSolution"

on:
  workflow_dispatch:

jobs:
  test-building:
    name: "Test building"
    runs-on: ${{ matrix.os }}
    env:
      DEVENV_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.com
      SLN_PATH: src\TestSolution\TestSolution.sln
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1
    - name: nuget restore
      shell: cmd
      run: |
        nuget restore "%SLN_PATH%"
    - name: compile debug
      shell: cmd
      run: |
#        "%DEVENV_PATH%" "%SLN_PATH%" /build debug
        msbuild "%SLN_PATH%" /p:Configuration=Debug
    - name: compile release
      shell: cmd
      run: |
#        "%DEVENV_PATH%" "%SLN_PATH%" /build release
        msbuild "%SLN_PATH%" /p:Configuration=Release