name: "Build TestSolution"

on:
  workflow_dispatch:

jobs:
  test-building:
    name: "Test building"
    runs-on: ${{ matrix.os }}
    env:
      DEVENV_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.com
      MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\MSBuild.exe"
      SLN_PATH: src\TestSolution\TestSolution.sln
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: msbuild restore
      shell: cmd
      run: |
        "%MSBUILD_PATH%" restore "%SLN_PATH%"
    - name: compile debug
      shell: cmd
      run: |
        "%MSBUILD_PATH%" "%SLN_PATH%" /p:Configuration=Debug
    - name: compile release
      shell: cmd
      run: |
        "%MSBUILD_PATH%" "%SLN_PATH%" /p:Configuration=Release