name: "Build TestSolution"

on:
  workflow_dispatch:

jobs:
  test-building:
    name: "Test building"
    runs-on: ${{ matrix.os }}
    env:
      SLN_PATH: src\TestSolution\TestSolution.sln
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
    - name: msbuild restore
      shell: cmd
      run: |
        msbuild /t:restore "%SLN_PATH%"
    - name: compile debug
      shell: cmd
      run: |
        msbuild "%SLN_PATH%" /p:Configuration=Debug
    - name: compile release
      shell: cmd
      run: |
        msbuild "%SLN_PATH%" /p:Configuration=Release