name: "Cosmos DB check"

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  testing:
    name: Testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04 ]
    steps:
      - name: Show NetAdapters
        run: |
          ifconfig
          $ipAddress = (hostname -I | awk '{print $1}')
          Write-Output "IpAddress = $ipAddress"
      - name: Start Azure Cosmos DB emulator
        run: |
          $ipAddress = (hostname -I | awk '{print $1}')
          $containerId = (docker create -p 8081:8081 -p 10251:10251 -p 10252:10252 -p 10253:10253 -p 10254:10254 -m 3g --cpus=2.0 -e AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10 -e AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=false -e AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=$ipAddress mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator)
          Write-Output "##vso[task.setvariable variable=cosmosDbContainerId]$containerId"
          docker start -a $containerId
      - name: Diagnostics
        run: |
          echo "ContainerId = $containerId"
          docker logs $containerId
      - name: Prepare emulator
        run: |
          ipAddress=$(hostname -I | awk '{print $1}')
          curl -k https://$ipAddress:8081/_explorer/emulator.pem > $(Agent.TempDirectory)/emulatorcert.crt
          sudo cp $(Agent.TempDirectory)/emulatorcert.crt /usr/local/share/ca-certificates/
          sudo update-ca-certificates
          echo "##vso[task.setvariable variable=cosmosDbEndpoint]https://$ipAddress:8081"
      - name: Clean Azure Cosmos DB emulator
        run: |
          if (-not $containerId) {
            docker rm -f $containerId
            sudo rm -f /usr/local/share/ca-certificates/emulatorcert.crt
          }
        if: always()