name: "Cosmos DB check"

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  testing:
    name: Testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04 ]
    steps:
      - name: Start Azure Cosmos DB emulator
        run: |
          netstat -tulpn | grep LISTEN
          Write-Output "Container creation..."
          $containerId = (docker create -p 8081:8081 -p 10251:10251 -p 10252:10252 -p 10253:10253 -p 10254:10254 -m 3g --cpus=2.0 --name=test-linux-emulator busybox)
          Write-Output "Container starting..."
          docker start $containerId
          Start-Sleep -Seconds 10
          $retriesCount = 10
          while ($isStarted -eq $false -and $retriesCount -ne 0) {
            $status = (docker ps -a --filter "NAMES==test-linux-emulator").STATUS
            if ($status.Contains('Up')) {
              Write-Output "Container $containerId started."
              break
            }
            if ($status.Contains('Exited')) {
              Write-Output "Container $containerId exited."
              break
            }
            Write-Output "Waiting for container $containerId to start"
            Write-Output (docker logs $containerId | Out-String)
            Start-Sleep -Seconds 5
            $retriesCount--
          }
          docker ps --all
          netstat -tulpn | grep LISTEN