name: Run unit tests

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.7
            toxenv: py37-test-pytest46
          - os: windows-2019
            python-version: 3.7
            toxenv: py37-test-pytest50
          - os: macos-latest
            python-version: 3.7
            toxenv: py37-test-pytest51
          - os: ubuntu-latest
            python-version: 3.7
            toxenv: py37-test-pytest52
          - os: windows-2019
            python-version: 3.8
            toxenv: py38-test-pytest53
          - os: ubuntu-latest
            python-version: 3.8
            toxenv: py38-test-pytest60
          - os: ubuntu-latest
            python-version: 3.9
            toxenv: py39-test-pytest61
          - os: ubuntu-latest
            python-version: 3.9
            toxenv: py39-test-pytest62
          - os: macos-latest
            python-version: 3.8
            toxenv: py38-test-pytestdev
          - os: ubuntu-latest
            python-version: '3.10'
            toxenv: py310-test-pytest70
            toxargs: --pre

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Tox
      run: python -m pip install tox
    - name: Run Tox
      run: tox ${{ matrix.toxargs }} -v -e ${{ matrix.toxenv }}