name: "Ubuntu images check"

on:
  workflow_dispatch:

jobs:
  testing:
    name: Testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Check execution
        shell: bash
        run: |
          versions=("2.1" "3.1" "5.0" "6.0")
          for version in ${versions[@]}; do
            release_url="https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/${version}/releases.json"
            curl ${release_url} -4 -sL -o "./${version}.json"
            releases=$(cat "./${version}.json")
            if [[ $version == "6.0" ]]; then
                sdks=("${sdks[@]}" $(echo "${releases}" | jq '.releases[]' | jq '.sdks[]?' | jq '.version' | grep -v preview | grep -v rc | grep -v display -m 1))
            else
                sdks=("${sdks[@]}" $(echo "${releases}" | jq '.releases[]' | jq '.sdk.version'))
                sdks=("${sdks[@]}" $(echo "${releases}" | jq '.releases[]' | jq '.sdks[]?' | jq '.version'))
            fi
            rm ./${version}.json
          done
          sortedSdks=$(echo ${sdks[@]} | tr ' ' '\n' | grep -v preview | grep -v rc | grep -v display | cut -d\" -f2 | sort -r | uniq -w 5)
          echo ${sortedSdks[@]}