name: "Ubuntu images check"

on:
  workflow_dispatch:

jobs:
  testing:
    name: Testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Check execution
        shell: pwsh
        run: |
          $containerId = (docker create busybox)
          docker start -a $containerId
          docker ps