name: "Ubuntu images check"

on:
  workflow_dispatch:

jobs:
  testing:
    name: Testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Check execution
        shell: pwsh
        run: |
          $containerId = (docker create mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator)
          Write-Output "conainerId: $containerId"
          docker start -a $containerId
          docker ps --all

      - name: Check execution 2
        shell: pwsh
        run: |
          docker run mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
          docker ps --all