name: "Windows images check"

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  testing:
    name: Testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2016, windows-2019, windows-2022 ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Check execution
        run: |
          (nuget help) -match "NuGet Version"