trigger: none

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-20.04'

jobs:
- job: Job
  displayName: 'Job'
  steps:
  - task: PowerShell@2
    name: startCosmosDb
    displayName: 'Wait for Cosmos'
    inputs:
      pwsh: true
      targetType: inline
      script: |
        $containerId = (docker create -p 8081:8081 -p 10251:10251 -p 10252:10252 -p 10253:10253 -p 10254:10254 -m 3g --cpus=2.0 -e AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10 -e AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=false -e AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1 mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator)
        docker start $containerId
        docker logs --timestamps --details $containerId
        docker ps --all
